added functionality for delete_word_left, delete_word_right and move_left/right_by_word for text_input
focus-editor/focus pull request #1
Opened 2023-04-27 21:17 UTC by aang521

2023-04-27 23:37 UTC, aang521 commented
Hi, that explains a lot 😅
I will take a look at it tomorrow. Would you prefer it it text input is also treated as byte offsets, or rather have me change my changes to treat it as character offsets?

2023-04-27 23:41 UTC, focus-editor commented
I think byte offsets is the way to go. I haven't touched that code in a long time, but I think there may be a couple of auxiliary functions for dealing with char offsets in the drawing code - feel free to remove them if they are no longer used elsewhere.

Thanks for your work! 💪

2023-04-28 11:09 UTC, aang521 commented
I think I fixed all the issues with multi byte characters.

2023-04-28 17:15 UTC, obiwanus requested changes
Looks much better now! That temporary limit of 5000 has been bothering me and now we can get rid of it.

I think the only thing left to do it the `text_input_type_char` function, which still uses char offsets and causes crashes when you type non-ascii chars.

Would you be able to make that change? And delete the `decode_utf8_string_to_temp_chars` and `get_char_offset` while you're at it?

2023-04-28 17:15 UTC, obiwanus commented on src/widgets/text_input.jai
> -    chars := decode_utf8_string_to_temp_chars(to_string(text), max_char = 5000);  // arbitrary number
So glad to see it gone - this function can finally retire.

2023-04-28 17:58 UTC, aang521 commented
Fixed the issue with typing non-ascii characters.
Also found and fixed some issues with deleting multibyte characters.

2023-04-28 18:08 UTC, merged

2023-04-28 18:08 UTC, focus-editor commented
Well done, thank you very much! 💪 

I noticed that the alt-delete shortcuts don't yet work, perhaps we should also add them later