Add "Save as" and "Delete current file" functionality
focus-editor/focus pull request #111
Opened 2023-07-29 05:44 UTC by SentientCoffee

Sometimes you want to duplicate a file on your filesystem or just delete it because you goofed. Well now you can do it from the editor without having to switch from your file explorer and back all the time :)

The delete current file option pops up a confirmation dialog just to be sure you want to delete the file, and even if you get past that and decide after that it was an accident, the buffer with all your file data is preserved so you can resave it if necessary.

With both of these functionalities in, a patch for renaming files should be pretty easy, if that's also something we want.

2023-07-29 07:31 UTC, focus-editor requested changes

2023-07-29 07:31 UTC, focus-editor commented on src/editors.jai
> +        save_buffer_to_disk(b, b_id);
Why was this change made?

2023-07-29 07:31 UTC, focus-editor commented on src/buffer.jai
> +    if buffer.has_file || buffer.file.full_path return buffer.file.name;
Please don't do it because if `buffer.has_file` is `false`, the context of `buffer.file` may contain garbage.

2023-07-29 07:31 UTC, focus-editor commented on src/widgets/delete_file_dialog.jai
> +buffer_to_delete: *Buffer;
This is wildly unsafe. Please never store pointers to editors (or buffers, for that matter), for any prolonged period of time (longer than one function).

Between the time the pointer to editor is stored and used the editor array may be reallocated and we'll crash.

Please use ids instead. Here as it seems you don't need the editor anyway.

2023-07-31 15:45 UTC, SentientCoffee commented on src/editors.jai
> +        session_notify_modified_buffer(editor.buffer_id); // @Cleanup? This doesn't seem to do anything.
Removed the comment.

2023-07-31 15:46 UTC, SentientCoffee commented on src/editors.jai
> +        save_buffer_to_disk(b, b_id);
I thought it was a possible shadowing bug, I can revert it back if needed.

2023-07-31 15:48 UTC, SentientCoffee commented on src/buffer.jai
> +    if buffer.has_file || buffer.file.full_path return buffer.file.name;
In what scenario would it have garbage?

2023-07-31 16:06 UTC, SentientCoffee commented on src/widgets/delete_file_dialog.jai
> +buffer_to_delete: *Buffer;
Fixed.

2023-07-31 21:20 UTC, focus-editor commented on src/buffer.jai
> +    if buffer.has_file || buffer.file.full_path return buffer.file.name;
I can't tell you right now, maybe currently there aren't such scenarios, but `has_file` was added there specifically to guard against that.

Maybe we could reconsider and see if we can rely on buffer.file.full_path being empty instead, but I'd need to go and look at the code, which I don't have the time for right now.

I'll try to have a look later and will get back to you on this.

2023-07-31 21:20 UTC, focus-editor commented
Thanks for the updated PR. I will have a closer look and test later today when I have some time.

2023-08-01 02:56 UTC, SentientCoffee commented on src/buffer.jai
> +    if buffer.has_file || buffer.file.full_path return buffer.file.name;
This is just a convenience for when you have a buffer that has a file name, from a file that used to exist on disk. If it really is that much of a hassle, I can revert this change as well, but it is nice to have the name already there if all you wanted to do was rename the file with a small tweak to the filename, for example.

2023-08-01 06:40 UTC, focus-editor requested changes
Just a couple of small things. 

I'm ready to merge when those are addressed. Regarding the `has_file` thing, let's merge it as is and I will make a note for myself to review the use of `has_file`.

Thanks

2023-08-01 06:40 UTC, focus-editor commented on src/draw.jai
> +        buffer    := open_buffers[buffer_id];
Why not take a pointer here to avoid a copy? Everywhere else when we get a buffer by id we do it by pointer (except for one place I just found, which should also be changed to a pointer)

2023-08-01 06:40 UTC, focus-editor commented on src/widgets/delete_file_dialog.jai
> +    buffer := open_buffers[editor.buffer_id];
Same here

2023-08-01 06:40 UTC, focus-editor commented on src/widgets/delete_file_dialog.jai
> +    defer unlock(*open_buffers_lock);
We only need to lock when we're adding a new buffer to the buffer array or are modifying the path-to-id hash table.

We're not doing it here, and the `delete_buffer_from_disk` function, which does it, locks the corresponding portion of the code itself, so it should be safe to not lock here in this function.

2023-08-01 16:54 UTC, SentientCoffee commented on src/draw.jai
> +        buffer    := open_buffers[buffer_id];
Changed to a pointer.

2023-08-01 16:54 UTC, SentientCoffee commented on src/widgets/delete_file_dialog.jai
> +    buffer := open_buffers[editor.buffer_id];
Changed to a pointer.

2023-08-01 16:54 UTC, SentientCoffee commented on src/widgets/delete_file_dialog.jai
> +    defer unlock(*open_buffers_lock);
Removed.

2023-08-01 21:22 UTC, merged

2023-08-01 21:22 UTC, focus-editor commented
Thank you @SentientCoffee !