add toggle_fullscreen command
focus-editor/focus pull request #149
Opened 2023-08-24 17:25 UTC by ustance

Since there is currently no way to go into fullscreen on Windows.

2023-08-24 21:24 UTC, focus-editor requested changes

2023-08-24 21:24 UTC, focus-editor commented on src/platform/linux.jai
> +    toggle_fullscreen(window, fullscreen, *fullscreen_info);
I'm assuming you meant `fullscreen_state` here and in `macos.jai`

2023-08-24 21:24 UTC, focus-editor commented on src/platform/macos.jai
> +fullscreen_state: Saved_Window_Info;
Does it work if this is put in `main.jai`? If yes then I'd propose to move it there to avoid unnecessary duplication.

2023-08-25 07:34 UTC, ustance commented on src/platform/macos.jai
> +fullscreen_state: Saved_Window_Info;
done

2023-08-25 22:10 UTC, merged