Persistent search highlights
focus-editor/focus pull request #239
Opened 2023-12-20 04:37 UTC by amasondev

Makes search highlighting stay visible after closing the search bar. This is similar to vim's `hlsearch` option.

Relevant discord msg: https://discord.com/channels/1106007785193345104/1126291418202251368/1153893543820140646

Question: should this be default behaviour or behind a config option?

2023-12-20 05:36 UTC, focus-editor requested changes
We need to refresh results in at least 2 more places - in `refresh_open_buffers` if the buffer is still dirty, and in `refresh_buffer_from_disk`, otherwise when a buffer is modified elsewhere the editor won't update the highlights.

2023-12-20 05:36 UTC, focus-editor commented on src/editors.jai
> +        }
Please put on one line with a `then` since we do it in this codebase when we can

2023-12-20 05:36 UTC, focus-editor commented on src/editors.jai
> +    }
Same here

2023-12-20 05:46 UTC, amasondev commented
> We need to refresh results in at least 2 more places - in `refresh_open_buffers` if the buffer is still dirty, and in `refresh_buffer_from_disk`, otherwise when a buffer is modified elsewhere the editor won't update the highlights.

Good catch. The change to refresh_all_editors_for_buffer catches both of these.

2023-12-20 05:55 UTC, merged

2023-12-23 04:52 UTC, focus-editor commented
This will now be disabled by default to avoid confusion. Please enable manually using `persist_local_search_results: true`