C# nested string interpolation highlighting
focus-editor/focus pull request #318
Opened 2024-03-10 03:33 UTC by audV

Added C# nested string interpolation highlighting by parsing interpolated string in sections broken up by the interpolated expression sections in {} (further details in code comments).

This required remembering if the parser was inside an interpolated string expression section and if the string was also a verbatim string. This was done by creating CSharp_Tokenizer (similar to other tokenizers) with the extra info to keep things thread safe.

Also updated the dereference operators (separate commit).

Tested on the following C# (built with Jai 0.1.086)
```
var
test = "thing";            //standard
test = "thi\"ng";          //standard " escaped
test = @"thing";           //verbatim
test = @"thi""ng";         //verbatim " escaped
            
test = $"thin{1}g";        //interpolated
test = $"thin{1 + Single.MinValue + (0x2A66__F__a * 10)}g"; //interpolated longer expression
test = $"thi\"n{1}g";      //interpolated " escaped
test = $"thi\"n{{{1}}}g";  //interpolated " escaped, bracket escaped
test = $"thi{1}n{2}g";     //interpolated multiple
            
test = @$"th""in{1}g";     //verbatim interpolated escaped
test = $@"th""in{1}g";     //interpolated verbatim escaped
            
test = $"thin{$"thin{1-1}g"}g";                          //interpolated nested
test = $"thin{$"th{1-1}in{1-2}g"}g";                     //interpolated multiple in nested
test = $"thin{$"thin{$"thin{3}g"}g"}g";                  //interpolated triple nested
test = $"thin{$"thin{1-1}g"}g_thin{$"thin{2-1}g"}g";     //interpolated nested multiple same levels
test = $"thin{$"thin{1-1}g"}g_thin{2}g";                 //interpolated nested multiple different levels
            
test = $"thin{$"th\"in{1-1}g"}g";                        //interpolated nested, nested " escape
test = $"thin{$"th{{in{1-1}g}}"}g";                      //interpolated nested, nested bracket escape
test = $"thin{$"th\"in{1-1}g"}g_thin{$"thin{2-1}g"}g";   //interpolated nested multiple same levels, nested " escape
test = $"thin{$"th\"in{1-1}g"}g_thin{2}g";               //interpolated nested multiple different levels, nested " escape
            
test = @$"thin{$"thin{1-1}g"}g";                         //verbatim interpolated nested
test = @$"thin{$"thin{1-1}g"}g_thin{$"thin{2-1}g"}g";    //verbatim interpolated nested multiple same levels
test = @$"thin{$"thin{1-1}g"}g_thin{2}g";                //verbatim interpolated nested multiple different levels

test = @$"thin{@$"th""in{1-1}g"}g";                      //verbatim interpolated nested, nested " escape
test = @$"thin{@$"th{{in{1-1}g}}"}g";                    //verbatim interpolated nested, nested bracket escape
test = @$"thin{@$"th""in{1-1}g"}g_thin{$"thin{2-1}g"}g"; //verbatim interpolated nested multiple same levels, nested " escape
test = @$"thin{@$"th""in{1-1}g"}g_thin{2}g";             //verbatim interpolated nested multiple different levels, nested " escape
            
test = @$"thin{$@"th""in{1-1}g"}g";                      //verbatim interpolated, interpolated verbatim nested, nested " escape
```
Comparison vs VS 2022
![image](https://github.com/focus-editor/focus/assets/77188323/a2f530fb-669c-46fc-b66e-17b2708b6e6d)

2024-03-10 06:00 UTC, focus-editor requested changes

2024-03-10 06:00 UTC, focus-editor commented on src/langs/csharp.jai
> +    interpolated_string_is_verbatim: [..] bool;
Can just do `interpolated_string_is_verbatim.allocator = temp;` here as mentioned above

2024-03-10 07:23 UTC, audV commented on src/langs/csharp.jai
> +        array_add(*interpolated_string_is_verbatim, is_verbatim,);
changed

2024-03-10 07:25 UTC, audV commented on src/langs/csharp.jai
> +    interpolated_string_is_verbatim: [..] bool;
Cool, I didn't know this was possible inside the struct aside from assigning a whole literal instance

2024-03-10 07:25 UTC, audV commented on src/langs/csharp.jai
> +    tokenizer.interpolated_string_is_verbatim.allocator = temp;
Changed

2024-03-11 04:03 UTC, focus-editor commented
Thanks for the PR!

2024-03-11 04:03 UTC, merged