Add revert_select_word_or_create_another_cursor and move_selection_to_next_word commands
focus-editor/focus pull request #445
Opened 2024-10-12 20:30 UTC by BuzzwordChief

Hello,

my workflow involves heavy usage of the `select_word_or_create_another_cursor` command. To make this command more powerful this pull request adds two new commands:
1. `revert_select_word_or_create_another_cursor`: Reverts the action of `select_word_or_create_another_cursor`
2. `move_selection_to_next_word`: Executes a `select_word_or_create_another_cursor` and deletes the previously 'newest' cursor. It basically allows you to skip a selection.

For a better comprehension see the following demo video:

https://github.com/user-attachments/assets/7a590fa5-3bed-4e1f-825a-e92b9692238f

2024-10-15 00:40 UTC, focus-editor requested changes
A very useful change, thanks for submitting it - please look at the requested changes

2024-10-15 00:40 UTC, focus-editor commented on src/editors.jai
> +            it.sel  = it.pos;
If the purpose of this is to remove selection, then `cursor.pos = cursor.sel` should suffice.

After testing this functionality I think we shouldn't remove selection when there's more than one cursor and the selected text is different

2024-10-15 00:40 UTC, focus-editor commented on src/editors.jai
> +{
In this codebase we don't put opening braces on a new line

2024-10-15 00:40 UTC, focus-editor commented on src/editors.jai
> +            // Maybe select_word_or_create_another_cursor should do nothing if it can't find a new word to select?
No, by wrapping the main cursor back to the original cursor we know we have selected everything, it is an intuitive behaviour which should be kept.

However, with this change it feels very unintuitive to remove the original cursor when this action is used after we've fully wrapped around. It should never remove the original cursor and it should always be possible to revert back to it by repeatedly using this action.

2024-10-19 14:49 UTC, BuzzwordChief commented on src/editors.jai
> +            it.sel  = it.pos;
Done, see line editor.jai:1800.

2024-10-19 14:50 UTC, BuzzwordChief commented on src/editors.jai
> +{
Done

2024-10-19 14:52 UTC, BuzzwordChief commented on src/editors.jai
> +            // Maybe select_word_or_create_another_cursor should do nothing if it can't find a new word to select?
Agreed. New version checks for original_cursor == main_cursor and deletes the cursor above the main_cursor in this case, see line editor.jai:1813.

2024-10-20 19:55 UTC, focus-editor commented
Seems to be working well now, thanks!

2024-10-20 19:55 UTC, merged