Add toggle_block_comment command
focus-editor/focus pull request #79
Opened 2023-06-24 08:10 UTC by Mulej

2023-06-24 08:45 UTC, focus-editor commented on src/editors.jai
> +            cursor.sel += 2 + move_count;
I'm sorry, I don't have the time right now to have a proper look - will do as soon as I can, but what's the purpose of this "2"?

2023-06-24 09:41 UTC, Mulej commented on src/editors.jai
> +            cursor.sel += 2 + move_count;
Ah, forgot to un-hard code the length of the comment start. Fixed now :)

2023-06-26 02:58 UTC, focus-editor requested changes
Thanks for your PR. I'd like to merge it but there are some issues.

1. I left a comment about depending on buffer colors - we really shouldn't do that.

2. Comment detection seems to be broken when you try to comment within a string (it doesn't work at all if you only do it with one cursor and not multiple)
![focus](https://github.com/focus-editor/focus/assets/119373822/9757614f-03af-473c-a9b8-
deea441a5fa8)

2023-06-26 02:58 UTC, focus-editor commented on src/editors.jai
> +        case .Focus_Config; toggle_comment(editor, buffer); // The config doesn't have block comments, fall back to toggle_comment.
I wonder if if would make sense to always fall back to `toggle_comment` for all languages?

2023-06-26 02:58 UTC, focus-editor commented on src/editors.jai
> +        }
I don't think we should depend on buffer coloring. Those systems are independent and it creates an unnecessary hard link between the two.

We are planning to change the way colors are assigned in the near future, there will not be a color per byte any more.

2023-06-26 06:44 UTC, Mulej commented on src/editors.jai
> +        }
Yeah, I'm using it to detect if we're in a comment to switch between adding them and removing them. How would you feel about saving an array of tokens from the tokenizer in the buffer for this kind of thing? It would also be useful for other things, like goto definition.

2023-06-26 06:44 UTC, Mulej commented on src/editors.jai
> +        case .Focus_Config; toggle_comment(editor, buffer); // The config doesn't have block comments, fall back to toggle_comment.
That makes more sense, will do.

2023-06-26 07:45 UTC, focus-editor commented on src/editors.jai
> +        }
What problems would there be if we just searched from the edges outwards until we either found the enclosing comments or we didn't? This way we don't have to depend on anything else. 

Buffers already have lots of metadata, I would avoid storing anything extra unless we really have to. The plan for symbol search and goto definition was to just populate a hashtable at parse time.

2023-06-26 09:26 UTC, Mulej commented on src/editors.jai
> +        }
The problem comes with having "/*" and "*/" in strings, that's why I was looking at the color buffer in the first place.
That being said, we could just ignore that edge case for now.

2023-06-26 10:06 UTC, focus-editor commented on src/editors.jai
> +        }
I don't think that's a big problem. We can definitely ignore it

2023-06-26 16:56 UTC, Mulej commented on src/editors.jai
> +        }
Modified to not use the color array. Also just noticed that github ate some asterisks in my previous comment...

2023-06-26 23:24 UTC, merged

2023-06-26 23:41 UTC, focus-editor commented
Thanks for your PR!

I've made a couple of minor changes to make the code more like the surrounding code, also added an early return for the default case https://github.com/focus-editor/focus/commit/a6ad5dec7a8e88b1f3c900bb9b6c3671fd058465